// Written by: Dan Jandel C. De Ramos

import java.util.Random;

public class CMPE102_lotNumGen_Java_Console{
    
    public static void lotteryNumberyGenerator(){

        Random randomizer = new Random();
        int[] lotteryNumbers = new int[7];
        
        for(int loop = 0; loop < lotteryNumbers.length; loop++){
            lotteryNumbers[loop] = randomizer.nextInt(10); // The array lotteryNumbers according to loop number will generate a pseudorandom value generated by the Random randomizer function from 0 to 9 (10 Elements)
            System.out.print(lotteryNumbers[loop] + " ");
        }
    }

    public static void main(String[] args) {
        System.out.print("Generated Lottery Numbers: ");
        lotteryNumberyGenerator();
    }
}