// Written by: Dan Jandel C. De Ramos

#include <iostream>
#include <random>

using namespace std;

void lotteryNumberGenerator(){
    int lotteryNumbers[7] = {};
    random_device randomizer; // Creating a randomizer
    uniform_int_distribution<int> lotteryNumber(0, 9); // Sets minimum and maximum value of randomizer which will be assinged to int variable lotteryNumber

    for(int loop = 0; loop < (sizeof(lotteryNumbers)/sizeof(int)); loop++){ //C++ obtains the sizeof() value in terms of bytes, which is 4x of int. In order to obtain int value, we must divide the sizeof operator value to sizeof(int) which is 4
        lotteryNumbers[loop] = lotteryNumber(randomizer); // The array, according to loop number will store a psuedorandom value generated by the random_device randomizer function
        cout << lotteryNumbers[loop] << " ";
    }
}

int main(){
    cout << "Generated Lottery Numbers: ";
    lotteryNumberGenerator();
}